name: decisionlab_umancapital
description: "Framework DecisionLab - UmanCapital"
publish_to: 'none'
version: 1.0.10+10

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
