Skip to content
passeggero23
DecisionLab-suite
Repository navigation
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
build_app
Update yaml.yml #23
All jobs
Run details
Annotations
1 error
build
failed 9 minutes ago in 1m 13s
Search logs
2s
0s
5s
59s
4s
Run # 1. Elimina solo la cartella Android corrotta, NON il pubspec
Recreating project ....
  android/app/build.gradle.kts (created)
  android/app/src/main/kotlin/com/example/umancapital/MainActivity.kt (created)
  android/build.gradle.kts (created)
  android/umancapital_android.iml (created)
  .gitignore (created)
  android/settings.gradle.kts (created)
  android/gradle.properties (created)
  android/.gitignore (created)
  android/app/src/profile/AndroidManifest.xml (created)
  android/app/src/debug/AndroidManifest.xml (created)
  android/app/src/main/res/values/styles.xml (created)
  android/app/src/main/res/drawable-v21/launch_background.xml (created)
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  android/app/src/main/res/values-night/styles.xml (created)
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  android/app/src/main/res/drawable/launch_background.xml (created)
  android/app/src/main/AndroidManifest.xml (created)
  android/gradle/wrapper/gradle-wrapper.properties (created)
  README.md (created)
  umancapital.iml (created)
  analysis_options.yaml (created)
  .idea/modules.xml (created)
  .idea/workspace.xml (created)
  .idea/runConfigurations/main_dart.xml (created)
  .idea/libraries/KotlinJavaRuntime.xml (created)
0s
0s
0s
0s
0s
0s
Footer
Â© 2026 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Community
Docs
Contact
Manage cookies
Do not share my personal information
