name: build_app
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: reset_totale_progetto
        run: |
          # 1. Creiamo un pubspec.yaml da zero per evitare l'errore 65
          echo "name: umancapital" > pubspec.yaml
          echo "environment:" >> pubspec.yaml
          echo "  sdk: '>=3.0.0 <4.0.0'" >> pubspec.yaml
          echo "dependencies:" >> pubspec.yaml
          echo "  flutter: { sdk: flutter }" >> pubspec.yaml
          
          # 2. Creiamo la struttura android pulita
          flutter create --project-name=umancapital . --platforms=android
          
          # 3. Scarichiamo le dipendenze
          flutter pub get

      - name: build_aab
        run: flutter build appbundle --release --no-sound-null-safety

      - name: upload_file
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: "**/build/app/outputs/bundle/release/app-release.aab"
