name: build_app
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Fix and Get
        run: |
          # 1. Crea la cartella android che manca (TUTTO MINUSCOLO!)
          flutter create --project-name=umancapital . --platforms=android
          # 2. Risolve l'errore della foto b6847786 (SDK missing)
          echo "environment: {sdk: '>=3.0.0 <4.0.0'}" > pubspec_fix.yaml
          cat pubspec.yaml >> pubspec_fix.yaml || true
          mv pubspec_fix.yaml pubspec.yaml
          flutter pub get

      - name: Build AAB
        # Aggiungiamo la protezione per il codice vecchio
        run: flutter build appbundle --release --no-sound-null-safety

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: "**/build/app/outputs/bundle/release/app-release.aab"
