name: build_app
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java_Setup
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Flutter_Setup
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Pulizia_e_Build
        run: |
          flutter create --project-name=umancapital . --platforms=android --overwrite
          echo "environment: {sdk: '>=3.0.0 <4.0.0'}" > pubspec.yaml
          echo "dependencies: {flutter: {sdk: flutter}}" >> pubspec.yaml
          flutter pub get
          flutter build appbundle --release --no-sound-null-safety

      - name: Caricamento_AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: "**/build/app/outputs/bundle/release/*.aab"
