name: build_app
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
          flutter create --project-name=umancapital . --platforms=android --overwrite
          echo "environment: {sdk: '>=3.0.0 <4.0.0'}" > pubspec.yaml
          echo "dependencies: {flutter: {sdk: flutter}}" >> pubspec.yaml
          flutter pub get
          flutter build appbundle --release --no-sound-null-safety
      - uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: "**/build/app/outputs/bundle/release/*.aab"
